server:
  port: 8080

spring:
  application:
    name: zuul-proxy
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**

eureka:
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

#zuul:
  #routes:
    #customer-service:
      #serviceId: customer-service
  #host:
    #socket-timeout-millis: 30000